### ISSUE TITLE
[lib-sass] Failed to load the atom-react-native-css package

### ISSUE THREAD

**Issue by xxsnakerxx** [TOP-Chao/atom-react-native-css#1] opened 2016-01-14 04:51 UTC
`cd ~/.atom/packages/atom-react-native-css/ && npm rebuild node-sass` wasn't help (still get the error at start)

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.2
### Stack Trace

Failed to load the atom-react-native-css package

```
At The `libsass` binding was not found in /Users/xxsnakerxx/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Error: The `libsass` binding was not found in /Users/xxsnakerxx/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/xxsnakerxx/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/xxsnakerxx/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/xxsnakerxx/.atom/packages/atom-react-native-css/index.js:6:12)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "dash",
      "language-gfm",
      "language-gfm",
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.3
atom-react-native-css, v0.0.2
atom-ternjs, v0.12.2
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
colornamer, v0.3.1
docblockr, v0.7.3
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
js-hyperclick, v1.4.1
language-babel, v2.7.3
language-javascript-jsx, v0.3.7
language-mako, v0.6.0
line-ending-converter, v1.3.2
linter, v1.11.3
linter-eslint, v5.2.7
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
pigments, v0.19.6
pretty-json, v0.4.1
project-manager, v2.7.3
react, v0.12.10
redux-snippets, v0.2.1
term3, v0.21.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment] 2016-01-14 05:12
My computer:
Atom Version: 1.4.0
System: Mac OS X 10.11.2
There is no such problem.

`Error source node-sass`
Because your nodejs version has changed. Node-sass needs to be re installed. So you try to uninstall and reinstall the package
Or enter the plugin directory to execute the command: `npm rebuild node-sass`

**Comment by xxsnakerxx** [comment] 2016-01-14 05:42
I've fixed this by adding `darwin-x64-46 binding.node` manually. [look here for details](http://stackoverflow.com/a/34334221/2866099)

**Comment by aeke** [comment] 2016-01-26 22:39
thanks @xxsnakerxx 

I downloaded ago darwin-x64-46 binding.node file and copy to **~/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor** folder

after enter this directory and execute the command **`npm rebuild node-sass`**

**Comment by rwuttke** [comment] 2016-02-07 22:57
Just to add onto that (not sure if I should create a new issue)

**atom version** 1.4.3
**node version** 5.5.0
**npm version** 3.6.0
**system info** Windows 10 x64

Thrown from v0.0.4 of the react-native-css package.

I am getting a similar error on Win 10 x64.

If I rebuild node-sass, then I get the following

```
> node-sass@3.4.2 install C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass
> node scripts/build.js

` C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-x64-47\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass
```

As can be seen the vendor version is a **64 bit version 47** for binding.node.

The exception that I am getting from the package in Atom is as follows

```
The `libsass` binding was not found in C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-46\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

As can been the vendor version being looked for is a **32 bit version 46** for binding.node

If I add the win32-ia32-46 binding.node and remove the x64 v 47 one, do the rebuild, it just re-gets the x64 version and reports that the binary is fine; exiting.

When I next start Atom, I get the following:

```
A dynamic link library (DLL) initialization routine failed.
C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-46\binding.node
```

And then atom generally crashes after that.

**Comment by luan-cestari** [comment] 2016-02-14 00:15
Got the same issue:
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: "Fedora release
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.4

### Stack Trace

Failed to load the atom-react-native-css package

```
At The `libsass` binding was not found in /home/lcestari/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Error: The `libsass` binding was not found in /home/lcestari/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/lcestari/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/lcestari/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/lcestari/.atom/packages/atom-react-native-css/lib/compile.js:7:12)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/lcestari/.atom/packages/atom-react-native-css/lib/index.js:5:15)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
```

### Commands

```
     -0:00.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ],
    "followSymlinks": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.3
atom-react-native-css, v0.0.4
autocomplete-paths, v1.0.2
dartlang, v0.5.4
flutter, v0.1.2
language-javascript-jsx, v0.3.7
linter, v1.11.3
nuclide, v0.116.0
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by luan-cestari** [comment] 2016-02-14 00:16
I tried `npm install -g node-sass` and `npm rebuild node-sass`

**Comment by lucasfeliciano** [comment] 2016-02-29 11:03
I'm getting this when I open atom:

[Enter steps to reproduce below:]
1. Open atom

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.4

### Stack Trace

Failed to load the atom-react-native-css package

```
At The `libsass` binding was not found in /Users/myUser/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Error: The `libsass` binding was not found in /Users/myUser/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/myUser/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/myUser/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/myUser/.atom/packages/atom-react-native-css/lib/compile.js:7:12)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/myUser/.atom/packages/atom-react-native-css/lib/index.js:5:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.4
atom-react-native-css, v0.0.4
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-eslint, v7.0.0
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
nucleus-dark-ui, v0.7.10
react, v0.14.1
react-es6-snippets, v0.3.0
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment] 2016-03-01 03:20
@lucasfeliciano Hi, this question is because `node-sass` installation fails. [look here for details](http://stackoverflow.com/questions/34326516/task-sass-not-found-using-grunt-with-patternlab/34334221#34334221)

**Comment by rwuttke** [comment] 2016-03-01 03:34
@TOP-Chao, you closed this without addressing all of the problems.

Those details DO NOT work on Windows, please read what I posted and you will see I can not do what that says to do.

In fact, my post says I tried that and it still fails.

Please re-open this.

**Comment by 94cstyles** [comment] 2016-03-01 03:41
@rwuttke oh, I'm sorry `node-sass` unsuccessful installation, I can not solve, you can go to [here](https://github.com/sass/node-sass/issues)  for help.

**Comment by rwuttke** [comment] 2016-03-01 04:02
@TOP-Chao Thanks for re-opening. I appreciate your speedy response.

**Comment by 758915145** [comment] 2016-03-15 09:47
那么，问题该怎么办解决呢？

**Comment by 94cstyles** [comment] 2016-03-15 09:53
node-sass我安装是成功的 不论是 win 还是 macos 。你可以尝试重新安装，或者升级下node版本，或者去[node-sass issues](https://github.com/sass/node-sass/issues)问作者。

**Comment by WriterLuo** [comment] 2016-03-18 07:43
我也遇到这个问题，目前暂时解决不了

**Comment by TOP-Chao** [comment] 2016-03-19 06:28
我将发布新版本，默认不支持`sass`文件，只支持`css`文件，并且不安装`node-sass`。需要使用`sass`文件，需要在选项中设置。
I will release a new version, the default does not support `sass` file, only support ` css` file, and do not install `node-sass`. Need to use `sass` file, you need to setting.

**Comment by 94cstyles** [comment] 2016-03-22 02:25
我也遇到了这个问题，问题原因是`node-sass`无法找到文件，需要你手动去下载。

```
At The `libsass` binding was not found in /Users/wenchao/Project/github/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
```

在/node_modules/node-sass/vendor/ 下创建目录**darwin-x64-46**
然后去[node-sass-binaries](https://github.com/sass/node-sass-binaries)下载对应系统的版本的文件
再把文件复制到/node_modules/node-sass/vendor/darwin-x64-46/目录下 并改文件名为:**binding.node**
最后重启atom。注意文件版本和系统版本一定要对，不然没有用。

---

I have encountered this problem, the cause of the problem is the `node-sass` not find the file, you need to manually download.

```
At The `libsass` binding was not found in /Users/wenchao/Project/github/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-46/binding.node
```

Create a directory **darwin-x64-46** in  /node_modules/node-sass/vendor/
Go to [node-sass-binaries](https://github.com/sass/node-sass-binaries) download the corresponding version of the file 
Copy the file to /node_modules/node-sass/vendor/darwin-x64-46/  
the file rename:**binding.node**
Restart atom。

**Comment by WriterLuo** [comment] 2016-03-23 03:07
期待新版本解决这个问题

**Comment by 94cstyles** [comment] 2016-03-24 02:41
The new version has been released

**Closed as completed by 94cstyles** 2016-03-24 02:41 UTC
